spring.application.name=.jobapplication.service
server.port=8083

spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.url=${REDIS_URL}

jwt.secret=${SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

jobposting.url=${JOBPOSTING_URL}

supabase.url=${SUPABASE_URL}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.bucket=${SUPABASE_BUCKET}

debug=true
