spring.application.name=.jobapplication.service
server.port=8083

debug=true

spring.config.import=optional:file:./.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.data.redis.url=${REDIS_URL}

jwt.secret=${SECRET}
jwt.internal.secret=${INTERNAL_SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jobposting.url=${JOBPOSTING_URL}
ia.url=${IA_URL}

supabase.url=${SUPABASE_URL}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.bucket=${SUPABASE_BUCKET}
